//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jinher.AMP.BTP.TPS.eInvoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.ejinshui.com/", ConfigurationName="eInvoService.IEInvoiceService")]
    public interface IEInvoiceService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfoResponse downloadEInvoiceInfo(Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfo request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfoResponse submitEInvoiceInfo(Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadEInvoiceInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadEInvoiceInfo", Namespace="http://service.ejinshui.com/", Order=0)]
        public Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfoBody Body;
        
        public downloadEInvoiceInfo() {
        }
        
        public downloadEInvoiceInfo(Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadEInvoiceInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public downloadEInvoiceInfoBody() {
        }
        
        public downloadEInvoiceInfoBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadEInvoiceInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadEInvoiceInfoResponse", Namespace="http://service.ejinshui.com/", Order=0)]
        public Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfoResponseBody Body;
        
        public downloadEInvoiceInfoResponse() {
        }
        
        public downloadEInvoiceInfoResponse(Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadEInvoiceInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public downloadEInvoiceInfoResponseBody() {
        }
        
        public downloadEInvoiceInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitEInvoiceInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitEInvoiceInfo", Namespace="http://service.ejinshui.com/", Order=0)]
        public Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfoBody Body;
        
        public submitEInvoiceInfo() {
        }
        
        public submitEInvoiceInfo(Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class submitEInvoiceInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public submitEInvoiceInfoBody() {
        }
        
        public submitEInvoiceInfoBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitEInvoiceInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitEInvoiceInfoResponse", Namespace="http://service.ejinshui.com/", Order=0)]
        public Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfoResponseBody Body;
        
        public submitEInvoiceInfoResponse() {
        }
        
        public submitEInvoiceInfoResponse(Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class submitEInvoiceInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public submitEInvoiceInfoResponseBody() {
        }
        
        public submitEInvoiceInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEInvoiceServiceChannel : Jinher.AMP.BTP.TPS.eInvoService.IEInvoiceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EInvoiceServiceClient : System.ServiceModel.ClientBase<Jinher.AMP.BTP.TPS.eInvoService.IEInvoiceService>, Jinher.AMP.BTP.TPS.eInvoService.IEInvoiceService {
        
        public EInvoiceServiceClient() {
        }
        
        public EInvoiceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EInvoiceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EInvoiceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EInvoiceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfoResponse Jinher.AMP.BTP.TPS.eInvoService.IEInvoiceService.downloadEInvoiceInfo(Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfo request) {
            return base.Channel.downloadEInvoiceInfo(request);
        }
        
        public string downloadEInvoiceInfo(string arg0) {
            Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfo inValue = new Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfo();
            inValue.Body = new Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfoBody();
            inValue.Body.arg0 = arg0;
            Jinher.AMP.BTP.TPS.eInvoService.downloadEInvoiceInfoResponse retVal = ((Jinher.AMP.BTP.TPS.eInvoService.IEInvoiceService)(this)).downloadEInvoiceInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfoResponse Jinher.AMP.BTP.TPS.eInvoService.IEInvoiceService.submitEInvoiceInfo(Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfo request) {
            return base.Channel.submitEInvoiceInfo(request);
        }
        
        public string submitEInvoiceInfo(string arg0) {
            Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfo inValue = new Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfo();
            inValue.Body = new Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfoBody();
            inValue.Body.arg0 = arg0;
            Jinher.AMP.BTP.TPS.eInvoService.submitEInvoiceInfoResponse retVal = ((Jinher.AMP.BTP.TPS.eInvoService.IEInvoiceService)(this)).submitEInvoiceInfo(inValue);
            return retVal.Body.@return;
        }
    }
}
